# Generated by Django 5.0.2 on 2024-02-25 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_agregue_columna_en_platos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheff',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cheffs',
            },
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='platoId',
            field=models.ForeignKey(db_column='plato_id', on_delete=django.db.models.deletion.PROTECT, related_name='ingredientes', to='gestion.plato'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='tipo',
            field=models.TextField(choices=[('entrada', 'ENTRADA'), ('plato_de_fondo', 'PLATO DE FONDO'), ('postre', 'POSTER')], default='entrada'),
        ),
        migrations.AlterField(
            model_name='preparacion',
            name='platoId',
            field=models.ForeignKey(db_column='plato_id', on_delete=django.db.models.deletion.PROTECT, related_name='preparaciones', to='gestion.plato'),
        ),
    ]
