"""agregue columna activo

Revision ID: 4af809a87524
Revises: 4882c26a7330
Create Date: 2024-01-26 21:02:21.358070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af809a87524'
down_revision = '4882c26a7330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), server_default='1', nullable=True))
        batch_op.alter_column('sexo', server_default='NINGUNO')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
