"""removi not null tabla pedido

Revision ID: ab8244705cd8
Revises: 6d9c2e50cfef
Create Date: 2024-02-07 20:04:51.615155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab8244705cd8'
down_revision = '6d9c2e50cfef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('man_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('man_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
